<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net11.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsTrimmable>true</IsTrimmable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<!-- 👇 .NET 11+ 配置 -->
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0'))">
		<Features>$(Features);runtime-async=on</Features>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Avalonia.Gif.Test" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="BD.Common" />
		<PackageReference Include="BD.Common.Mvvm" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LibAPNG\LibAPNG.csproj" />
		<ProjectReference Include="..\..\..\src\Avalonia.Base.Internals\Avalonia.Base.Internals.csproj" />
	</ItemGroup>
</Project>
